// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/ingest/v1/ingest.proto

package ingestv1

import (
	common "github.com/Ragnar-Engine/ragnar-system/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestTextRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Text            string                  `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Metadata        map[string]string       `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestMetadata *common.RequestMetadata `protobuf:"bytes,3,opt,name=request_metadata,json=requestMetadata,proto3,oneof" json:"request_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestTextRequest) Reset() {
	*x = IngestTextRequest{}
	mi := &file_api_proto_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTextRequest) ProtoMessage() {}

func (x *IngestTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTextRequest.ProtoReflect.Descriptor instead.
func (*IngestTextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IngestTextRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IngestTextRequest) GetRequestMetadata() *common.RequestMetadata {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

type IngestTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTextResponse) Reset() {
	*x = IngestTextResponse{}
	mi := &file_api_proto_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTextResponse) ProtoMessage() {}

func (x *IngestTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTextResponse.ProtoReflect.Descriptor instead.
func (*IngestTextResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestTextResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

var File_api_proto_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_api_proto_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	" api/proto/ingest/v1/ingest.proto\x12\tingest.v1\x1a\x1dapi/proto/common/common.proto\"\x8a\x02\n" +
	"\x11IngestTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.ingest.v1.IngestTextRequest.MetadataEntryR\bmetadata\x12G\n" +
	"\x10request_metadata\x18\x03 \x01(\v2\x17.common.RequestMetadataH\x00R\x0frequestMetadata\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_request_metadata\"5\n" +
	"\x12IngestTextResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId2Z\n" +
	"\rIngestService\x12I\n" +
	"\n" +
	"IngestText\x12\x1c.ingest.v1.IngestTextRequest\x1a\x1d.ingest.v1.IngestTextResponseBEZCgithub.com/Ragnar-Engine/ragnar-system/api/proto/ingest/v1;ingestv1b\x06proto3"

var (
	file_api_proto_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_api_proto_ingest_v1_ingest_proto_rawDescData []byte
)

func file_api_proto_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_api_proto_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_api_proto_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ingest_v1_ingest_proto_rawDesc), len(file_api_proto_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_api_proto_ingest_v1_ingest_proto_rawDescData
}

var file_api_proto_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_ingest_v1_ingest_proto_goTypes = []any{
	(*IngestTextRequest)(nil),      // 0: ingest.v1.IngestTextRequest
	(*IngestTextResponse)(nil),     // 1: ingest.v1.IngestTextResponse
	nil,                            // 2: ingest.v1.IngestTextRequest.MetadataEntry
	(*common.RequestMetadata)(nil), // 3: common.RequestMetadata
}
var file_api_proto_ingest_v1_ingest_proto_depIdxs = []int32{
	2, // 0: ingest.v1.IngestTextRequest.metadata:type_name -> ingest.v1.IngestTextRequest.MetadataEntry
	3, // 1: ingest.v1.IngestTextRequest.request_metadata:type_name -> common.RequestMetadata
	0, // 2: ingest.v1.IngestService.IngestText:input_type -> ingest.v1.IngestTextRequest
	1, // 3: ingest.v1.IngestService.IngestText:output_type -> ingest.v1.IngestTextResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_ingest_v1_ingest_proto_init() }
func file_api_proto_ingest_v1_ingest_proto_init() {
	if File_api_proto_ingest_v1_ingest_proto != nil {
		return
	}
	file_api_proto_ingest_v1_ingest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ingest_v1_ingest_proto_rawDesc), len(file_api_proto_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_api_proto_ingest_v1_ingest_proto_depIdxs,
		MessageInfos:      file_api_proto_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_api_proto_ingest_v1_ingest_proto = out.File
	file_api_proto_ingest_v1_ingest_proto_goTypes = nil
	file_api_proto_ingest_v1_ingest_proto_depIdxs = nil
}
