// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/proto/embed/v1/embed.proto

package embedv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmbedService_EmbedText_FullMethodName    = "/embed.v1.EmbedService/EmbedText"
	EmbedService_GetModelInfo_FullMethodName = "/embed.v1.EmbedService/GetModelInfo"
)

// EmbedServiceClient is the client API for EmbedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbedServiceClient interface {
	EmbedText(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error)
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*ModelInfo, error)
}

type embedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbedServiceClient(cc grpc.ClientConnInterface) EmbedServiceClient {
	return &embedServiceClient{cc}
}

func (c *embedServiceClient) EmbedText(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedTextResponse)
	err := c.cc.Invoke(ctx, EmbedService_EmbedText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embedServiceClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, EmbedService_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbedServiceServer is the server API for EmbedService service.
// All implementations must embed UnimplementedEmbedServiceServer
// for forward compatibility.
type EmbedServiceServer interface {
	EmbedText(context.Context, *EmbedTextRequest) (*EmbedTextResponse, error)
	GetModelInfo(context.Context, *GetModelInfoRequest) (*ModelInfo, error)
	mustEmbedUnimplementedEmbedServiceServer()
}

// UnimplementedEmbedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbedServiceServer struct{}

func (UnimplementedEmbedServiceServer) EmbedText(context.Context, *EmbedTextRequest) (*EmbedTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedText not implemented")
}
func (UnimplementedEmbedServiceServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedEmbedServiceServer) mustEmbedUnimplementedEmbedServiceServer() {}
func (UnimplementedEmbedServiceServer) testEmbeddedByValue()                      {}

// UnsafeEmbedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbedServiceServer will
// result in compilation errors.
type UnsafeEmbedServiceServer interface {
	mustEmbedUnimplementedEmbedServiceServer()
}

func RegisterEmbedServiceServer(s grpc.ServiceRegistrar, srv EmbedServiceServer) {
	// If the following call panics, it indicates UnimplementedEmbedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbedService_ServiceDesc, srv)
}

func _EmbedService_EmbedText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServiceServer).EmbedText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbedService_EmbedText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServiceServer).EmbedText(ctx, req.(*EmbedTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbedService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbedService_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServiceServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbedService_ServiceDesc is the grpc.ServiceDesc for EmbedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embed.v1.EmbedService",
	HandlerType: (*EmbedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmbedText",
			Handler:    _EmbedService_EmbedText_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _EmbedService_GetModelInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/embed/v1/embed.proto",
}
