// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/embed/v1/embed.proto

package embedv1

import (
	common "github.com/Ragnar-Engine/ragnar-system/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedTextRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Text          string                  `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model         *string                 `protobuf:"bytes,2,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextRequest) Reset() {
	*x = EmbedTextRequest{}
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextRequest) ProtoMessage() {}

func (x *EmbedTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextRequest.ProtoReflect.Descriptor instead.
func (*EmbedTextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_embed_v1_embed_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedTextRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *EmbedTextRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmbedTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Dimensions    int32                  `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextResponse) Reset() {
	*x = EmbedTextResponse{}
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextResponse) ProtoMessage() {}

func (x *EmbedTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextResponse.ProtoReflect.Descriptor instead.
func (*EmbedTextResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_embed_v1_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedTextResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedTextResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedTextResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

type GetModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *string                `protobuf:"bytes,1,opt,name=model,proto3,oneof" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelInfoRequest) Reset() {
	*x = GetModelInfoRequest{}
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelInfoRequest) ProtoMessage() {}

func (x *GetModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelInfoRequest.ProtoReflect.Descriptor instead.
func (*GetModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_embed_v1_embed_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelInfoRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

type ModelInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Dimensions     int32                  `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	MaxInputTokens int32                  `protobuf:"varint,3,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_embed_v1_embed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_embed_v1_embed_proto_rawDescGZIP(), []int{3}
}

func (x *ModelInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelInfo) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *ModelInfo) GetMaxInputTokens() int32 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

var File_api_proto_embed_v1_embed_proto protoreflect.FileDescriptor

const file_api_proto_embed_v1_embed_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/embed/v1/embed.proto\x12\bembed.v1\x1a\x1dapi/proto/common/common.proto\"\x92\x01\n" +
	"\x10EmbedTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\x05model\x18\x02 \x01(\tH\x00R\x05model\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.common.RequestMetadataH\x01R\bmetadata\x88\x01\x01B\b\n" +
	"\x06_modelB\v\n" +
	"\t_metadata\"g\n" +
	"\x11EmbedTextResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\":\n" +
	"\x13GetModelInfoRequest\x12\x19\n" +
	"\x05model\x18\x01 \x01(\tH\x00R\x05model\x88\x01\x01B\b\n" +
	"\x06_model\"k\n" +
	"\tModelInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\x05R\n" +
	"dimensions\x12(\n" +
	"\x10max_input_tokens\x18\x03 \x01(\x05R\x0emaxInputTokens2\x98\x01\n" +
	"\fEmbedService\x12D\n" +
	"\tEmbedText\x12\x1a.embed.v1.EmbedTextRequest\x1a\x1b.embed.v1.EmbedTextResponse\x12B\n" +
	"\fGetModelInfo\x12\x1d.embed.v1.GetModelInfoRequest\x1a\x13.embed.v1.ModelInfoBCZAgithub.com/Ragnar-Engine/ragnar-system/api/proto/embed/v1;embedv1b\x06proto3"

var (
	file_api_proto_embed_v1_embed_proto_rawDescOnce sync.Once
	file_api_proto_embed_v1_embed_proto_rawDescData []byte
)

func file_api_proto_embed_v1_embed_proto_rawDescGZIP() []byte {
	file_api_proto_embed_v1_embed_proto_rawDescOnce.Do(func() {
		file_api_proto_embed_v1_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_embed_v1_embed_proto_rawDesc), len(file_api_proto_embed_v1_embed_proto_rawDesc)))
	})
	return file_api_proto_embed_v1_embed_proto_rawDescData
}

var file_api_proto_embed_v1_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_embed_v1_embed_proto_goTypes = []any{
	(*EmbedTextRequest)(nil),       // 0: embed.v1.EmbedTextRequest
	(*EmbedTextResponse)(nil),      // 1: embed.v1.EmbedTextResponse
	(*GetModelInfoRequest)(nil),    // 2: embed.v1.GetModelInfoRequest
	(*ModelInfo)(nil),              // 3: embed.v1.ModelInfo
	(*common.RequestMetadata)(nil), // 4: common.RequestMetadata
}
var file_api_proto_embed_v1_embed_proto_depIdxs = []int32{
	4, // 0: embed.v1.EmbedTextRequest.metadata:type_name -> common.RequestMetadata
	0, // 1: embed.v1.EmbedService.EmbedText:input_type -> embed.v1.EmbedTextRequest
	2, // 2: embed.v1.EmbedService.GetModelInfo:input_type -> embed.v1.GetModelInfoRequest
	1, // 3: embed.v1.EmbedService.EmbedText:output_type -> embed.v1.EmbedTextResponse
	3, // 4: embed.v1.EmbedService.GetModelInfo:output_type -> embed.v1.ModelInfo
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_embed_v1_embed_proto_init() }
func file_api_proto_embed_v1_embed_proto_init() {
	if File_api_proto_embed_v1_embed_proto != nil {
		return
	}
	file_api_proto_embed_v1_embed_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_embed_v1_embed_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_embed_v1_embed_proto_rawDesc), len(file_api_proto_embed_v1_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_embed_v1_embed_proto_goTypes,
		DependencyIndexes: file_api_proto_embed_v1_embed_proto_depIdxs,
		MessageInfos:      file_api_proto_embed_v1_embed_proto_msgTypes,
	}.Build()
	File_api_proto_embed_v1_embed_proto = out.File
	file_api_proto_embed_v1_embed_proto_goTypes = nil
	file_api_proto_embed_v1_embed_proto_depIdxs = nil
}
